package cn.jsprun.utils;
import java.util.regex.Pattern;
public class JsprunCodeProp {
	public static String bbcode_str[] = { "\\[/color\\]", "\\[/size\\]", "\\[/font\\]", "\\[/align\\]",
			"\\[b\\]", "\\[/b\\]", "\\[i\\]", "\\[/i\\]", "\\[u\\]", "\\[/u\\]", "\\[list\\]", "\\[list\\=1\\]",
			"\\[list\\=a\\]", "\\[list\\=A\\]", "\\[\\*\\]", "\\[/list\\]", "\\[indent\\]", "\\[/indent\\]",
			"\\[/float\\]", "\\[quote\\]", "\\[/quote\\]","\\[/align\\]","\\[/email\\]","\\[/fly\\]","\\[sup\\]","\\[/sup\\]","\\[sub\\]","\\[/sub\\]","\\[fly\\]"};
	public static String bbcode_speciald[] = {"(\\B|\\b)?\\[url=www.([^\\[\"']+?)\\](.+?)\\[/url\\](\\B|\\b)?","(\\B|\\b)?\\[url=(https?|ftp|gopher|news|telnet|rtsp|mms|callto|bctp|ed2k|thunder|synacast){1}:\\/\\/([^\\[\"']+?)\\](.+?)\\[/url\\](\\B|\\b)?","(\\B|\\b)?\\[email\\]\\s*([a-z0-9\\-_.+]+)@([a-z0-9\\-_]+[.][a-z0-9\\-_.]+)\\s*\\[/email\\](\\B|\\b)?","(\\B|\\b)?\\[email=([a-z0-9\\-_.+]+)@([a-z0-9\\-_]+[.][a-z0-9\\-_.]+)\\](.+?)\\[/email\\](\\B|\\b)?","(\\B|\\b)?\\[color=([#\\w]+?)\\](\\B|\\b)?","(\\B|\\b)?\\[size=(\\d+?)\\](\\B|\\b)?","(\\B|\\b)?\\[size=(\\d+(\\.\\d+)?(px|pt|in|cm|mm|pc|em|ex|%)+?)\\](\\B|\\b)?","(\\B|\\b)?\\[font=([^\\[\\<]+?)\\](\\B|\\b)?","(\\B|\\b)?\\[align=(left|center|right)\\](\\B|\\b)?","(\\B|\\b)?\\[float=(left|right)\\](\\B|\\b)?","(\\B|\\b)?\\[url\\]\\s*(https?:\\/\\/|ftp:\\/\\/|gopher:\\/\\/|news:\\/\\/|telnet:\\/\\/|rtsp:\\/\\/|mms:\\/\\/|callto:\\/\\/|bctp:\\/\\/|ed2k:\\/\\/|thunder:\\/\\/|synacast:\\/\\/){1}([^\\[\"']+?)\\s*\\[/url\\](\\B|\\b)?","(\\B|\\b)?\\[url\\]\\s*(www.){1}([^\\[\"']+?)\\s*\\[/url\\](\\B|\\b)?"};
	public static String bbcode_replaced[] = {"<a href=\"http://www.$2\" target=\"_blank\">www.$2</a>","<a href=\"$2://$3\" target=\"_blank\">$4</a>","<a href=\"mailto:$2@$3\">$2@$3</a>","<a href=\"mailto:$2@$3\">$2@$3</a>","<font color=\"$2\">","<font size=\"$2\">","<font style=\"font-size: $2\">","<font face=\"$2 \">","<p align=\"$2\">","<span style=\"float: $2;\">","<a href=\"$2$3\" target=\"_blank\">$2$3</a>","<a href=\"http://www.$3\" target=\"_blank\">www.$3</a>"};
	public static String ramessage = "<object classid=\"clsid:CFCDAA03-8BE4-11CF-B84B-0020AFBBCCFA\" width=\"{1}\" height=\"32\"><param name=\"autostart\" value=\"{3}\" /><param name=\"src\" value=\"{4}\" /><param name=\"controls\" value=\"controlpanel\" /><param name=\"console\" value=\"media_XHm_\" /><embed src=\"{4}\" type=\"audio/x-pn-realaudio-plugin\" controls=\"ControlPanel\" autostart=\"{3}\" console=\"media_XHm_\" width=\"{1}\" height=\"32\"></embed></object>";
	public static String rmmessage = "<object classid=\"clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA\" width=\"{1}\" height=\"{2}\"><param name=\"autostart\" value=\"{3}\" /><param name=\"src\" value=\"{4}\" /><param name=\"controls\" value=\"imagewindow\" /><param name=\"console\" value=\"media_jYq_\" /><embed src=\"{4}\" type=\"audio/x-pn-realaudio-plugin\" controls=\"IMAGEWINDOW\" console=\"media_jYq_\" width=\"{1}\" height=\"{2}\"></embed></object><br /><object classid=\"clsid:CFCDAA03-8BE4-11CF-B84B-0020AFBBCCFA\" width=\"{1}\" height=\"32\"><param name=\"src\" value=\"{4}\" /><param name=\"controls\" value=\"controlpanel\" /><param name=\"console\" value=\"media_jYq_\" /><embed src=\"{4}\" type=\"audio/x-pn-realaudio-plugin\" controls=\"ControlPanel\"&nbsp;&nbsp;console=\"media_jYq_\" width=\"{1}\" height=\"32\"></embed></object>";
	public static String wmamessage = "<object classid=\"clsid:6BF52A52-394A-11d3-B153-00C04F79FAA6\" width=\"{1}\" height=\"64\"><param name=\"autostart\" value=\"{3}\" /><param name=\"url\" value=\"{4}\" /><embed src=\"{4}\" autostart=\"{3}\" type=\"audio/x-ms-wma\" width=\"{1}\" height=\"64\"></embed></object>";
	public static String wmvmessage = "<object classid=\"clsid:6BF52A52-394A-11d3-B153-00C04F79FAA6\" width=\"{1}\" height=\"{2}\"><param name=\"autostart\" value=\"{3}\" /><param name=\"url\" value=\"{4}\" /><embed src=\"{4}\" autostart=\"{3}\" type=\"video/x-ms-wmv\" width=\"{1}\" height=\"{2}\"></embed></object>";
	public static String mp3message = "<object classid=\"clsid:6BF52A52-394A-11d3-B153-00C04F79FAA6\" width=\"{1}\" height=\"64\"><param name=\"autostart\" value=\"{3}\" /><param name=\"url\" value=\"{4}\" /><embed src=\"{4}\" autostart=\"{3}\" type=\"application/x-mplayer2\" width=\"{1}\" height=\"64\"></embed></object>";
	public static String othermessage = "<object classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\" width=\"{1}\" height=\"{2}\"><param name=\"autostart\" value=\"{3}\" /><param name=\"src\" value=\"{4}\" /><embed controller=\"true\" width=\"{1}\" height=\"{2}\" src=\"{4}\" autostart=\"{3}\"></embed></object>";
	public static String bbcode_img[]={"(\\B|\\b)?\\[img=(\\d{1,4})[x|,](\\d{1,4})\\]\\s*([^\\[\\<\r\n]+?)\\s*\\[/img\\](\\B|\\b)?","(\\B|\\b)?\\[img\\]\\s*([^\\[\\<\r\n]+?)\\s*\\[/img\\](\\B|\\b)?"};
	public static String bbcode_imgreplace[]={"<img width=\"$2\" height=\"$3\" src=\"$4\" border=\"0\" alt=\"\" />","<img src=\"$2\" border=\"0\" onclick=\"zoom(this)\" onload=\"attachimg(this, \'load\')\" alt=\"\" />"};
	public static String bbcode_imgsp[]={"<a href=\"$4\" target=\"_blank\">$4</a>","<a href=\"$2\" target=\"_blank\">$2</a>"};
	public static Pattern pCode = Pattern.compile("(?s)\\s*\\[code(=(.*?))?\\](.*?)\\[/code\\]\\s*", Pattern.DOTALL); 
}
