<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<jsp:include flush="true" page="header.jsp" />
<div id="nav"><a href="${settings.indexname}">${settings.bbname}</a> &raquo; <c:if test="${extrafid!=null}"><a href="my.jsp?item=${myitem}"></c:if><c:choose><c:when test="${myitem=='threads'}"><bean:message key="my_threads"/></c:when><c:when test="${myitem=='posts'}"><bean:message key="my_replies"/></c:when><c:when test="${myitem=='favorites'&&type=='thread'}"><bean:message key="my_favorite_threads"/></c:when><c:when test="${myitem=='favorites'&&type=='forum'}"><bean:message key="myfavforums"/></c:when><c:when test="${myitem=='subscriptions'}"><bean:message key="my_subscription_threads"/></c:when><c:when test="${myitem=='grouppermission'}"> <bean:message key="permission_group_search"/></c:when><c:when test="${myitem=='polls'}"><bean:message key="my_poll"/></c:when><c:when test="${myitem=='tradestats'||myitem=='selltrades'||myitem=='buytrades'||myitem=='tradethreads'}"><bean:message key="my_trades"/></c:when><c:when test="${myitem=='reward'}"><bean:message key="my_rewards"/></c:when><c:when test="${myitem=='activities'}"><bean:message key="my_activities"/></c:when><c:when test="${myitem=='debate'}"><bean:message key="my_debate"/></c:when><c:when test="${myitem=='video'}"><bean:message key="my_video"/></c:when><c:when test="${myitem=='buddylist'}"><bean:message key="my_buddylist"/></c:when><c:when test="${myitem=='promotion'}"><bean:message key="post_my_advisit"/></c:when><c:otherwise><bean:message key="my"/>...</c:otherwise></c:choose><c:if test="${extrafid!=null}"> &raquo; ${forumname}</c:if></div>
<div class="container"><div class="content">
<div class="mainbox"><c:choose><c:when test="${myitem=='threads'}"><jsp:include flush="true" page="my_threads.jsp" /></c:when><c:when test="${myitem=='posts'}"><jsp:include flush="true" page="my_posts.jsp" /></c:when><c:when test="${myitem=='favorites'}"><jsp:include flush="true" page="my_favorites.jsp" /></c:when><c:when test="${myitem=='subscriptions'}"><jsp:include flush="true" page="my_subscriptions.jsp" /></c:when><c:when test="${myitem=='grouppermission'}"><jsp:include flush="true" page="my_grouppermission.jsp" /></c:when><c:when test="${myitem=='polls'}"><jsp:include flush="true" page="my_polls.jsp" /></c:when><c:when test="${myitem=='tradestats'}"><jsp:include flush="true" page="my_tradestats.jsp" /></c:when><c:when test="${myitem=='tradethreads'}"><jsp:include flush="true" page="my_tradethreads.jsp" /></c:when><c:when test="${myitem=='selltrades'||myitem=='buytrades'}"><jsp:include flush="true" page="my_trades.jsp" /></c:when><c:when test="${myitem=='reward'}"><jsp:include flush="true" page="my_reward.jsp" /></c:when><c:when test="${myitem=='activities'}"><jsp:include flush="true" page="my_activities.jsp" /></c:when><c:when test="${myitem=='debate'}"><jsp:include flush="true" page="my_debate.jsp" /></c:when><c:when test="${myitem=='video'}"><jsp:include flush="true" page="my_video.jsp" /></c:when><c:when test="${myitem=='buddylist'}"><jsp:include flush="true" page="my_buddylist.jsp" /></c:when><c:when test="${myitem=='promotion'}"><jsp:include flush="true" page="my_promotion.jsp" /></c:when><c:otherwise><jsp:include flush="true" page="my_index.jsp" /></c:otherwise></c:choose></div>
<c:if test="${!empty multi.multipage}"><div class="pages_btns">${multi.multipage}</div></c:if>
</div><div class="side"><jsp:include flush="true" page="personal_navbar.jsp" /></div></div>
<jsp:include flush="true" page="footer.jsp" />